<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>audit</string>
	</array>
	<key>name</key>
	<string>TNS Audit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#check</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>check</key>
		<dict>
			<key>begin</key>
			<string>(&lt;)(\w+?)( type)?(\s*\:.*?)?(&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tnsaudit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tnsaudit</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tnsaudit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.tnsaudit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#description</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xsl_stmt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiple_value_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#other_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^\s*#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.source.tnsaudit</string>
		</dict>
		<key>description</key>
		<dict>
			<key>begin</key>
			<string>^\s*(description)\s*:\s*(\")((\\.|[^\"])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\")(?!\w)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.name.tag.tnsaudit</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s}]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.tnsaudit</string>
		</dict>
		<key>multiple_value_tag</key>
		<dict>
			<key>begin</key>
			<string>^\s*(sql_types|sql_expect|value_data)\s*:\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>other_keywords</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)(NO|YES|NULL)(?=[\s\,])</string>
			<key>name</key>
			<string>meta.keyword.tnsaudit</string>
		</dict>
		<key>other_tags</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(audit_policy_subcategory|reg_key|reg_item|reg_ignore_hku_users|wmi_key|wmi_attribute|wmi_request|wmi_namespace|required|aws_action|systemvalue|system|file_extension|file|info|cmd|solution|type|see_also|item|value_type|regex_replace|max_size|only_show|known_good|request)\s*:\s*</string>
			<key>name</key>
			<string>meta.tag.tnsaudit</string>
		</dict>
		<key>reference</key>
		<dict>
			<key>begin</key>
			<string>^\s*(reference)\s*:\s*(\"|\')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"|\')(?!\w)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.reference.tnsaudit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xref</string>
				</dict>
			</array>
		</dict>
		<key>regex</key>
		<dict>
			<key>begin</key>
			<string>^\s*(regex|expect|not_expect|context)\s*:\s*(\"|\')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"|\')(?!\w)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp</string>
				</dict>
			</array>
		</dict>
		<key>sql</key>
		<dict>
			<key>begin</key>
			<string>^\s*(sql_request)\s*:\s*(\"|\')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"|\')(?!\w)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\"|\')</string>
			<key>end</key>
			<string>(\"|\')$</string>
			<key>name</key>
			<string>string.quoted.tnsaudit</string>
		</dict>
		<key>type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(kerberos_policy|password_policy|audit_policy|lockout_policy|dont_echo_cmd|check_type|value_type|right_type|reg_option|check_option|type)\s*:\s*(\w+)</string>
			<key>name</key>
			<string>meta.type.tag.tnsaudit</string>
		</dict>
		<key>xref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.tnsaudit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^\|]+)(\|)([^,\"]+)(,)?</string>
			<key>name</key>
			<string>keyword.operator.tnsaudit</string>
		</dict>
		<key>xsl_stmt</key>
		<dict>
			<key>begin</key>
			<string>^\s*(xsl_stmt)\s*:\s*(\"|\')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tnsaudit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"|\')(?!\w)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.tnsaudit</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml.xsl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tnsaudit</string>
	<key>uuid</key>
	<string>c5312048-2e1d-450d-8da2-f415ac92dfd4</string>
</dict>
</plist>
